<a href="https://colab.research.google.com/github/srijitaaa2005/MY-WORKS-DEEP-LEARNING-/blob/main/PyTorch_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [68]:
import numpy as np
import pandas as pd
import torch
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [69]:
df=pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [70]:
df.shape

(569, 33)

In [71]:
df.drop(columns=['id','Unnamed: 32'],inplace = True)
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [72]:
df.shape

(569, 31)

In [73]:
df['diagnosis'].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [74]:
y=df['diagnosis']
X=df.iloc[:,1:]

X

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [75]:
y

0      M
1      M
2      M
3      M
4      M
      ..
564    M
565    M
566    M
567    M
568    B
Name: diagnosis, Length: 569, dtype: object

In [76]:
X_train, X_test, y_train, y_test= train_test_split(X,y,test_size=0.2,random_state=1)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((455, 30), (114, 30), (455,), (114,))

In [77]:
scalar=StandardScaler()
X_train=scalar.fit_transform(X_train)
X_test=scalar.transform(X_test)

In [78]:
X_train

array([[ 1.0449852 ,  0.29708512,  1.01044815, ...,  1.21839781,
         0.29811854,  0.08380738],
       [ 1.68141074, -1.14098169,  1.70338066, ...,  0.69716372,
        -0.88595033, -0.41234747],
       [-1.44260855, -1.12732916, -1.4504636 , ..., -1.52233766,
         0.1807324 , -0.33657109],
       ...,
       [ 0.82638686,  1.17539807,  0.86625411, ...,  1.10638475,
         0.72853438,  3.02284824],
       [-0.05077356,  0.43133503, -0.11146165, ..., -0.54050588,
        -1.1207226 , -0.44903285],
       [-0.32748032, -0.21260945, -0.39904866, ..., -0.98109057,
        -1.52732096, -1.31985978]])

In [79]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [80]:
y_test

array([0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0])

In [81]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available")

GPU is available
Using GPU: Tesla T4

**NUMPY ARRAYS TO PYTORCH TENSORS**

In [82]:
X_train=torch.from_numpy(X_train).float()
X_test=torch.from_numpy(X_test).float()
y_train=torch.from_numpy(y_train).float()
y_test=torch.from_numpy(y_test).float()

In [83]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

(torch.Size([455, 30]),
 torch.Size([114, 30]),
 torch.Size([455]),
 torch.Size([114]))

In [84]:
X_train

tensor([[ 1.0450,  0.2971,  1.0104,  ...,  1.2184,  0.2981,  0.0838],
        [ 1.6814, -1.1410,  1.7034,  ...,  0.6972, -0.8860, -0.4123],
        [-1.4426, -1.1273, -1.4505,  ..., -1.5223,  0.1807, -0.3366],
        ...,
        [ 0.8264,  1.1754,  0.8663,  ...,  1.1064,  0.7285,  3.0228],
        [-0.0508,  0.4313, -0.1115,  ..., -0.5405, -1.1207, -0.4490],
        [-0.3275, -0.2126, -0.3990,  ..., -0.9811, -1.5273, -1.3199]])

**DATASET & DATALOADER**

In [85]:
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):
  def __init__(self,features,labels):
    self.features=features
    self.labels=labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self, index):
    return self.features[index], self.labels[index]

In [86]:
train_dataset=CustomDataset(X_train, y_train)
test_dataset=CustomDataset(X_test, y_test)

In [87]:
train_dataset[10]

(tensor([-0.3690,  2.1766, -0.4035, -0.4149, -1.1027, -0.9018, -0.3455, -0.6645,
         -0.9010, -0.8406, -0.7005,  0.2355, -0.6734, -0.5136,  0.4563, -0.2362,
          0.2443, -0.6784, -0.4312, -0.3687, -0.5035,  1.5973, -0.5577, -0.5122,
         -0.4258, -0.6087, -0.1382, -0.7601, -0.8723, -0.6746]),
 tensor(0.))

In [88]:
test_dataset[10]

(tensor([-0.8781, -0.5744, -0.8673, -0.8045,  0.8250, -0.5204, -0.7383, -0.6297,
         -0.3574,  0.1013, -0.7524,  0.2825, -0.7497, -0.5815, -0.6079, -0.9089,
         -0.7312, -0.7002, -0.4034, -0.5867, -0.7990,  0.1170, -0.8136, -0.7212,
          0.2148, -0.6979, -0.8106, -0.6200,  0.1926, -0.2903]),
 tensor(0.))

**CREATE DATALOADER**

In [89]:
train_loader=DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader=DataLoader(test_dataset, batch_size=32, shuffle=True)

**DEFINNING THE MODEL**

In [90]:
import torch.nn as nn

In [91]:
'''class MySimpleNN():
  def __init__(self,X):
    self.weights=torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True)'''


class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__() #constructor of the parent class is invoked
    self.linear=nn.Linear(num_features,1)
    self.sigmoid=nn.Sigmoid()


  #forward pass
  '''def forward_pass(self,X):
    z=torch.matmul(X,self.weights)+self.bias
    y_pred=torch.sigmoid(z)
    return y_pred'''

  def forward(self, features):
    out=self.linear(features)
    out=self.sigmoid(out)
    return out


  '''def loss_function(self,y_pred,y):
    #clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred=torch.clamp(y_pred, epsilon, 1-epsilon)

    #calculate loss
    loss = - (y_train * torch.log(y_pred) + (1-y_train) * torch.log(1-y_pred)).mean()
    return loss'''

**IMPORTANT PARAMETERS**

In [92]:
learning_rate=0.1
epochs=30

In [93]:
loss_function=nn.BCELoss()

**TRAINING PIPELINE**

In [94]:
# #converting training and testing data to float 32 from 64 since nn.Linear layer weights are float32 (Float) by default
# X_train = X_train.float()
# y_train = y_train.float()
# X_test = X_test.float()
# y_test = y_test.float()

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

#create model and move to GPU
model = Model(X_train.shape[1]).to(device)

#move data to GPU
X_train = X_train.to(device)
y_train = y_train.to(device)
X_test = X_test.to(device)
y_test = y_test.to(device)

#create optimizer
optimizer=torch.optim.SGD(model.parameters(), lr=learning_rate)

for i in range(epochs):

  for batch_features, batch_labels in train_loader:
    batch_features = batch_features.to(device)
    batch_labels = batch_labels.to(device)

    #forward pass
    '''y_pred=model.forward_pass(X_train)'''
    '''y_pred=model(X_train)'''
    y_pred=model(batch_features)

    #loss calculate
    '''loss=model.loss_function(y_pred,y_train)'''
    '''loss=loss_function(y_pred,y_train.view(-1,1))'''
    loss=loss_function(y_pred,batch_labels.view(-1,1))

    #clear gradient
    optimizer.zero_grad()

    #backward pass
    loss.backward()

    #parameters update
    '''with torch.no_grad():
      model.linear.weight -= lr*model.linear.weight.grad
      model.linear.bias -= lr*model.linear.bias.grad'''

    optimizer.step()

    #zero gradient
    '''model.linear.weight.grad.zero_()
    model.linear.bias.grad.zero_()'''

  #print loss for each epoch
  if (i + 1) % 10 == 0:
    print(f'Epoch: {i+1} Loss: {loss.item()}')

Epoch: 10 Loss: 0.026317354291677475
Epoch: 20 Loss: 0.0873386412858963
Epoch: 30 Loss: 0.023614982143044472

In [95]:
model.linear.weight

Parameter containing:
tensor([[ 0.3648,  0.5073,  0.6341,  0.5248,  0.1572, -0.0075,  0.5600,  0.6314,
          0.1475, -0.3769,  0.4353, -0.0956,  0.5704,  0.5511,  0.0824, -0.2306,
         -0.1842,  0.1499, -0.0819, -0.3160,  0.8637,  0.7393,  0.7957,  0.6390,
          0.6147,  0.1008,  0.5787,  0.4984,  0.4221,  0.2366]],
       device='cuda:0', requires_grad=True)

**VISUALIZE THE MODEL**

In [96]:
!pip install torchinfo

from torchinfo import summary
summary(model,input_size=(1,30)) #30 inputs and 1 output neuron

Requirement already satisfied: torchinfo in /usr/local/lib/python3.12/dist-packages (1.8.0)

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
Model                                    [1, 1]                    --
├─Linear: 1-1                            [1, 1]                    31
├─Sigmoid: 1-2                           [1, 1]                    --
==========================================================================================
Total params: 31
Trainable params: 31
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
==========================================================================================
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
==========================================================================================

In [97]:
print(next(model.parameters()).device)

cuda:0

**EVALUATION**

In [98]:
with torch.no_grad():
  y_pred=model(X_test)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5415512323379517

In [99]:
print(X_train.device)

cuda:0

In [100]:
#model evaluation using testloader
model.eval() #set the model to evaluation mode
accuracy_list=[]

with torch.no_grad():
  for batch_features, batch_labels in test_loader:

    batch_features = batch_features.to(device)
    batch_labels = batch_labels.to(device)

    y_pred=model(batch_features)
    y_pred=(y_pred>0.5).float()


    #calculate accuracy for current batch
    batch_accuracy=(y_pred.view(-1)==batch_labels).float().mean().item()
    accuracy_list.append(batch_accuracy)

#calculate overall accuracy
overall_accuracy=sum(accuracy_list)/len(accuracy_list)
print(f'Accuracy: {overall_accuracy:.4f}')

Accuracy: 0.9766