<a href="https://colab.research.google.com/github/srijitaaa2005/MY-WORKS-DEEP-LEARNING-/blob/main/Student_performance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/DEEP LEARNING/data.csv',encoding='latin1')

df.head()

Mounted at /content/drive

   Socioeconomic Score  Study Hours  Sleep Hours  Attendance (%)  Grades
0              0.95822          3.4          8.2            53.0    47.0
1              0.85566          3.2          5.9            55.0    35.0
2              0.68025          3.2          9.3            41.0    32.0
3              0.25936          3.2          8.2            47.0    34.0
4              0.60447          3.8         10.0            75.0    33.0

In [2]:
df.shape

(1388, 5)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1388 entries, 0 to 1387
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Socioeconomic Score  1388 non-null   float64
 1   Study Hours          1388 non-null   float64
 2   Sleep Hours          1388 non-null   float64
 3   Attendance (%)       1388 non-null   float64
 4   Grades               1388 non-null   float64
dtypes: float64(5)
memory usage: 54.3 KB

In [4]:
df.duplicated().sum()

np.int64(0)

In [5]:
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

X

      Socioeconomic Score  Study Hours  Sleep Hours  Attendance (%)
0                 0.95822          3.4          8.2            53.0
1                 0.85566          3.2          5.9            55.0
2                 0.68025          3.2          9.3            41.0
3                 0.25936          3.2          8.2            47.0
4                 0.60447          3.8         10.0            75.0
...                   ...          ...          ...             ...
1383              0.44549          5.5          8.0            51.0
1384              0.52466          4.9          6.5            63.0
1385              0.88197          3.9          6.2            54.0
1386              0.47336          3.5          7.3            61.0
1387              0.58119          3.7          9.7            79.0

[1388 rows x 4 columns]

In [6]:
y

0       47.0
1       35.0
2       32.0
3       34.0
4       33.0
        ...
1383    41.0
1384    37.0
1385    36.0
1386    34.0
1387    35.0
Name: Grades, Length: 1388, dtype: float64

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((1110, 4), (278, 4), (1110,), (278,))

In [8]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X_train_scaled = sc.fit_transform(X_train)
X_test_scaled = sc.transform(X_test)

In [16]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

model=Sequential()

model.add(Dense(4,activation='relu',input_dim=4))
model.add(Dense(3,activation='relu'))
model.add(Dense(2,activation='relu'))
model.add(Dense(1,activation='linear'))

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 4)              │            20 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 3)              │            15 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 2)              │             8 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 46 (184.00 B)

 Trainable params: 46 (184.00 B)

 Non-trainable params: 0 (0.00 B)

In [17]:
model.compile(optimizer='Adam',loss='mean_squared_error',metrics=['mean_absolute_error'])
model.fit(X_train_scaled,y_train,epochs=50)

Epoch 1/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 1740.5983 - mean_absolute_error: 40.6573
Epoch 2/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1730.9438 - mean_absolute_error: 40.5342
Epoch 3/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1716.6877 - mean_absolute_error: 40.3503
Epoch 4/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1696.1577 - mean_absolute_error: 40.0843
Epoch 5/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1667.3284 - mean_absolute_error: 39.7066
Epoch 6/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1627.3483 - mean_absolute_error: 39.1754
Epoch 7/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1572.7131 - mean_absolute_error: 38.4380
Epoch 8/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1498.5061 - mean_absolute_error: 37.4029
Epoch 9/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1402.1249 - mean_absolute_error: 36.0087
Epoch 10/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1282.3896 - mean_absolute_error: 34.1545
Epoch 11/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1141.2749 - mean_absolute_error: 31.8054
Epoch 12/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 987.9339 - mean_absolute_error: 28.9529
Epoch 13/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 832.7062 - mean_absolute_error: 25.7033
Epoch 14/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 689.3849 - mean_absolute_error: 22.4292
Epoch 15/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 565.1883 - mean_absolute_error: 19.6315
Epoch 16/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 462.4478 - mean_absolute_error: 17.4758
Epoch 17/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 375.4259 - mean_absolute_error: 15.7247
Epoch 18/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 302.4908 - mean_absolute_error: 14.1217
Epoch 19/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 238.7367 - mean_absolute_error: 12.5273
Epoch 20/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 186.6791 - mean_absolute_error: 11.0787
Epoch 21/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 145.7593 - mean_absolute_error: 9.7694
Epoch 22/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 114.9600 - mean_absolute_error: 8.6536
Epoch 23/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 92.2559 - mean_absolute_error: 7.7718
Epoch 24/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 76.4485 - mean_absolute_error: 7.0667
Epoch 25/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 65.1296 - mean_absolute_error: 6.5315
Epoch 26/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 56.9764 - mean_absolute_error: 6.1096
Epoch 27/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50.8097 - mean_absolute_error: 5.7659
Epoch 28/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 46.1080 - mean_absolute_error: 5.4883
Epoch 29/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 42.2047 - mean_absolute_error: 5.2412
Epoch 30/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 39.0862 - mean_absolute_error: 5.0337
Epoch 31/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 36.4447 - mean_absolute_error: 4.8506
Epoch 32/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 34.2393 - mean_absolute_error: 4.6855
Epoch 33/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 32.2080 - mean_absolute_error: 4.5351
Epoch 34/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 30.4716 - mean_absolute_error: 4.4023
Epoch 35/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 28.9302 - mean_absolute_error: 4.2742
Epoch 36/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 27.5645 - mean_absolute_error: 4.1651
Epoch 37/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 26.2749 - mean_absolute_error: 4.0526
Epoch 38/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 25.1066 - mean_absolute_error: 3.9615
Epoch 39/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 24.0625 - mean_absolute_error: 3.8672
Epoch 40/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 23.0788 - mean_absolute_error: 3.7829
Epoch 41/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 22.1717 - mean_absolute_error: 3.6975
Epoch 42/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.3282 - mean_absolute_error: 3.6284
Epoch 43/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.5131 - mean_absolute_error: 3.5598
Epoch 44/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 19.7284 - mean_absolute_error: 3.4799
Epoch 45/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 19.0170 - mean_absolute_error: 3.4130
Epoch 46/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18.3574 - mean_absolute_error: 3.3544
Epoch 47/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17.7323 - mean_absolute_error: 3.2906
Epoch 48/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17.1172 - mean_absolute_error: 3.2366
Epoch 49/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16.5546 - mean_absolute_error: 3.1868
Epoch 50/50
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16.0033 - mean_absolute_error: 3.1326

In [18]:
y_pred=model.predict(X_test_scaled)

from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)
print(r2)

9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
0.8569586571426668